// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ah9OFOW17xHIm-spX8UQThDd5HMlSl8',
    appId: '1:748988669685:web:763bd999ceb23ed0606fbc',
    messagingSenderId: '748988669685',
    projectId: 'app-financeiro-flutter',
    authDomain: 'app-financeiro-flutter.firebaseapp.com',
    storageBucket: 'app-financeiro-flutter.firebasestorage.app',
    measurementId: 'G-CB946Z537L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwsBMfN5uP-STIafVc5qQpf0eNhhem_4',
    appId: '1:748988669685:android:e0ff03c322c84cde606fbc',
    messagingSenderId: '748988669685',
    projectId: 'app-financeiro-flutter',
    storageBucket: 'app-financeiro-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqkGC7MOd6Pyg04z1fx85pTG9i7tfwME0',
    appId: '1:748988669685:ios:3e613fc3f36c5757606fbc',
    messagingSenderId: '748988669685',
    projectId: 'app-financeiro-flutter',
    storageBucket: 'app-financeiro-flutter.firebasestorage.app',
    iosBundleId: 'com.example.aplicacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqkGC7MOd6Pyg04z1fx85pTG9i7tfwME0',
    appId: '1:748988669685:ios:3e613fc3f36c5757606fbc',
    messagingSenderId: '748988669685',
    projectId: 'app-financeiro-flutter',
    storageBucket: 'app-financeiro-flutter.firebasestorage.app',
    iosBundleId: 'com.example.aplicacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ah9OFOW17xHIm-spX8UQThDd5HMlSl8',
    appId: '1:748988669685:web:2f7a643db6800fd0606fbc',
    messagingSenderId: '748988669685',
    projectId: 'app-financeiro-flutter',
    authDomain: 'app-financeiro-flutter.firebaseapp.com',
    storageBucket: 'app-financeiro-flutter.firebasestorage.app',
    measurementId: 'G-W6C31ZT6QL',
  );
}
